FROM bitnami/spark

USER root

# Install required packages
RUN install_packages wget build-essential zlib1g-dev libffi-dev

# Download and install Python 3.11
RUN wget https://www.python.org/ftp/python/3.11.6/Python-3.11.6.tgz \
    && tar -xzf Python-3.11.6.tgz \
    && cd Python-3.11.6 \
    && ./configure \
    && make \
    && make install \
    && cd .. \
    && rm -rf Python-3.11.6 Python-3.11.6.tgz

RUN wget https://jdbc.postgresql.org/download/postgresql-42.2.20.jar -P /opt/bitnami/spark/jars

# Set Python 3.11 as the default Python version
RUN ln -s /usr/local/bin/python3.11 /usr/bin/python \
    && ln -s /usr/local/bin/python3.11 /usr/bin/python3

# Set the PATH to prioritize /usr/local/bin
ENV PATH /usr/local/bin:$PATH

# Verify the default Python version
RUN python --version

# Set environment variables for PySpark
ENV PYSPARK_PYTHON=/usr/local/bin/python3.11
ENV PYTHONPATH=/usr/local/bin/python3.11
ENV PYSPARK_DRIVER_PYTHON=/usr/local/bin/python3.11
